#!/bin/bash
PREFIX=/opt
GCC_VERSION=4.8.2
PYTHON_VERSION=2.7.6
GCC_PREFIX=${PREFIX}/gcc-${GCC_VERSION}
PYTHON_PREFIX=${PREFIX}/python-${PYTHON_VERSION}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PYTHON_PREFIX}/lib
export PATH=${PYTHON_PREFIX}/bin:${PATH}
export CC=${GCC_PREFIX}/bin/gcc
export CXX=${GCC_PREFIX}/bin/g++
